/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.23
 * Generated at: 2022-10-26 15:59:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import DatabaseServlets.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("DatabaseServlets");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    <!DOCTYPE html>\n");
      out.write("    <html lang=\"en\">\n");
      out.write("\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=yes\">\n");
      out.write("        <link\n");
      out.write("            href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap\"\n");
      out.write("            rel=\"stylesheet\">\n");
      out.write("        <title>HOME</title>\n");
      out.write("        <!-- Bootstrap core CSS -->\n");
      out.write("        <link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("        <!-- Additional CSS Files -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/fontawesome.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/logoscope-master.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/owl.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/animate.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://unpkg.com/swiper@7/swiper-bundle.min.css\" />\n");
      out.write("\n");
      out.write("        <style>\n");
      out.write("            .p {\n");
      out.write("                margin-top: 2.5cm;\n");
      out.write("                font-size: 1cm;\n");
      out.write("                font-family: Georgia, 'Times New Roman', Times, serif;\n");
      out.write("                color: #fff;\n");
      out.write("                background-color: #e75e8d;\n");
      out.write("                border-radius: 20px;\n");
      out.write("                border-style: groove;\n");
      out.write("                border-color: #fff;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .user {\n");
      out.write("                display: inline-block;\n");
      out.write("                margin-left: 8cm;\n");
      out.write("                text-align: center;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .upload {\n");
      out.write("                display: inline-block;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            button {\n");
      out.write("                margin-left: 2cm;\n");
      out.write("                margin-right: 1.5cm;\n");
      out.write("                margin-top: 3cm;\n");
      out.write("                font-size: 14px;\n");
      out.write("                color: #fff;\n");
      out.write("                background-color: #e75e8d;\n");
      out.write("                padding: 8px 20px;\n");
      out.write("                display: inline-block;\n");
      out.write("                border-radius: 30px;\n");
      out.write("                border-color: #ffff;\n");
      out.write("                border-style: groove;\n");
      out.write("                font-weight: 400;\n");
      out.write("                text-transform: capitalize;\n");
      out.write("                letter-spacing: 0.5px;\n");
      out.write("                margin-bottom: 15cm;\n");
      out.write("\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            button:hover {\n");
      out.write("                background-color: #27292a;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("\n");
      out.write("        <!-- ***** Header Area Start ***** -->\n");
      out.write("        <header class=\"header-area header-sticky\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-12\">\n");
      out.write("                        <nav class=\"main-nav\">\n");
      out.write("                            <!-- ***** Logo Start ***** -->\n");
      out.write("                            <a href=\"index.jsp\" class=\"logo\">\n");
      out.write("                                <img src=\"assets/images/logo.png\" alt=\"\">\n");
      out.write("                            </a>\n");
      out.write("                            <!-- ***** Logo End ***** -->\n");
      out.write("                            <!-- ***** Menu Start ***** -->\n");
      out.write("                            <ul class=\"nav\">\n");
      out.write("                                <li><a href=\"index.jsp\">HOME</a></li>\n");
      out.write("                                <li><a href=\"SearchImage.jsp\">SEARCH</a></li>\n");
      out.write("                                <li><a href=\"register.jsp\">REGISTER</a></li>\n");
      out.write("                                <li><a href=\"login.jsp\">LOGIN</a></li>\n");
      out.write("                                <li class=\"dropdown\">\n");
      out.write("                                    <div class=\"dropbutton\">Categories +\n");
      out.write("                                        <div class=\"dropdown-content\">\n");
      out.write("                                            <a href=\"BlackAndWhite\">Black and White</a>\n");
      out.write("                                            <a href=\"Alphabets\">ALPHABETS</a>\n");
      out.write("                                            <a href=\"Bold\" class=\"active\">BOLD</a>\n");
      out.write("                                            <a href=\"Minimal\">MINIMAL</a>\n");
      out.write("                                            <a href=\"Fancy\">FANCY</a>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </li>\n");
      out.write("                                <!-- <li><a href=\"GrabUserServlet\">Profile<img src=\"assets/images/profile-header.jpg\" alt=\"\"></a></li> -->\n");
      out.write("                                <li><a href=\"GrabUserServlet\">My Profile <img src=\"assets/images/profile.jpg\"></a></li>\n");
      out.write("                            </ul>\n");
      out.write("                            <!-- ***** Menu End ***** -->\n");
      out.write("                        </nav>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </header>\n");
      out.write("\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("                    <div class=\"page-content\">\n");
      out.write("\n");
      out.write("                        <!-- Welcome -->\n");
      out.write("                        <header class=\"w3-container w3-center\" style=\"padding: 128px 16px\">\n");
      out.write("                            <h1 class=\"w3-margin w3-jumbo\">Welcome to Logoscope!</h1>\n");
      out.write("                            <p class=\"w3-xlarge\">For all your sticker browsing and logo needs.</p>\n");
      out.write("                        </header>\n");
      out.write("\n");
      out.write("                        <!-- About Our Service -->\n");
      out.write("                        <div class=\"w3-row-padding w3-padding-24 w3-container\">\n");
      out.write("                            <div class=\"w3-content\">\n");
      out.write("                                <div class=\"w3-onefourth\">\n");
      out.write("                                    <h1>About our Service</h1>\n");
      out.write("                                    <p>We provide an easy, secure and\n");
      out.write("                                        user-friendly way to download logos and stickers online. Go ahead! Try to make\n");
      out.write("                                        an account and browse to your heart's\n");
      out.write("                                        content. Feel free to check some of the\n");
      out.write("                                        exceptional categories images we have here. -- Account login required 😁</p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- ***** Popular Logo Start ***** -->\n");
      out.write("                        <div class=\"live-stream\">\n");
      out.write("                            <div class=\"col-lg-12\">\n");
      out.write("                                <div class=\"heading-section\">\n");
      out.write("                                    <h4><em>Most Popular</em> Logos</h4>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                                    <div class=\"item\">\n");
      out.write("                                        <div class=\"thumb\">\n");
      out.write("                                            <a href=\"GrabImageServlet?id=99\">\n");
      out.write("                                                <img src=\"assets/images/id 99.png\" alt=\"\"><br>\n");
      out.write("                                            </a>\n");
      out.write("                                            <p class=\"w3-center w3-large\">Black And White 8</p>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                                    <div class=\"item\">\n");
      out.write("                                        <div class=\"thumb\">\n");
      out.write("                                            <a href=\"GrabImageServlet?id=34\">\n");
      out.write("                                                <img src=\"assets/images/id 34.png\" alt=\"\"><br>\n");
      out.write("                                            </a>\n");
      out.write("                                            <p class=\"w3-center w3-large\">L</p>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                                    <div class=\"item\">\n");
      out.write("                                        <div class=\"thumb\">\n");
      out.write("                                            <a href=\"GrabImageServlet?id=118\">\n");
      out.write("                                                <img src=\"assets/images/id 118.png\" alt=\"\"><br>\n");
      out.write("                                            </a>\n");
      out.write("                                            <p class=\"w3-center w3-large\">Fancy 36</p>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                                    <div class=\"item\">\n");
      out.write("                                        <div class=\"thumb\">\n");
      out.write("                                            <a href=\"GrabImageServlet?id=85\">\n");
      out.write("                                                <img src=\"assets/images/id 85.png\" alt=\"\"><br>\n");
      out.write("                                            </a>\n");
      out.write("                                            <p class=\"w3-center w3-large\">Minimal 5</p>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- ***** Popular Logo End ***** -->\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- Footer -->\n");
      out.write("        <footer class=\"w3-container w3-padding-24 w3-center w3-opacity\">\n");
      out.write("            <div class=\"w3-large w3-padding-28\">\n");
      out.write("            <p>\n");
      out.write("                Created for Dynamic Web Application Project in TIB by team Aquamarine!\n");
      out.write("                <br> Want our code? Sorry you can't have it! 😜\n");
      out.write("            </p>\n");
      out.write("            </div>\n");
      out.write("        </footer>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
